openapi: 3.0.2
info:
  version: 1.0.0
  title: Issues Taiga
  description: "This is the Open API documentation for the REST API of our beloved application **Issues** deployed at <https://falta-link/>. <br>All operations are executable. All of the  operations requires authentication, you must **Authorize** your request by providing the token value you got when you created the tweet."
servers:
  # Added by API Auto Mocking Plugin
  - url: 'http://44.199.252.242:8080/'
paths:
  /issues:
    get:
      tags:
      - issues
      summary: Retrieves all the Issues
      operationId: index
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Issue'
    post:
      tags:
      - issues
      summary: Adds a new Issue to the set of issues
      operationId: addIssue
      requestBody:
        description: Provide the necessary fields to generate a new Issue
        content:
          application/json:
            schema:
              required:
              - subject
              type: object
              properties:
                subject:
                  type: string
                  minLength: 4
                  example: 'My subject'
                description:
                  type: string
                  minLength: 4
                  maxLength: 280
                  example: 'My description'
                typeIssue:
                  type: integer
                  minimum: 0
                  maximum: 3
                  example: 0
                severityIssue:
                  type: integer
                  minimum: 0
                  maximum: 4
                  example: 0
                priorityIssue:
                  type: integer
                  minimum: 0
                  maximum: 2
                  example: 0
                statusIssue:
                  type: integer
                  minimum: 0
                  maximum: 6
                  example: 0
        required: true
      responses:
        201:
          description: Issue created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewIssue'
        400:
          description: 'Error: Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error400'
      security:
      - ApiKeyAuth: [] 
  /issues/{issueId}:
    get:
      tags: 
      - issues
      summary: Finds an Issue by its ID
      description: Returns a single Issue
      operationId: getIssueById
      parameters:
      - name: issueId
        in: path
        description: ID of the Tweet to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
          200:
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Issue'
          404:
            description: 'Error: Not Found'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorExample:
                    $ref: '#/components/examples/error404'
          403:
            description: 'Error: Forbidden'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorExample:
                    $ref: '#/components/examples/error403'
    put:
      tags:
        - issues
      summary: Update an existing Issue with the new parameters passed
      description: Update an existing pet by Id
      operationId: updateIssue
      parameters:
      - name: issueId
        in: path
        description: ID of the Tweet to return
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: Update an existent pet in the store
        content:
          application/json:
            schema:
              properties:
                subject:
                  type: string
                  minLength: 4
                  example: 'My subject'
                description:
                  type: string
                  minLength: 4
                  maxLength: 280
                  example: 'My description'
                typeIssue:
                  type: integer
                  minimum: 0
                  maximum: 3
                  example: 0
                severityIssue:
                  type: integer
                  minimum: 0
                  maximum: 4
                  example: 0
                priorityIssue:
                  type: integer
                  minimum: 0
                  maximum: 2
                  example: 0
                statusIssue:
                  type: integer
                  minimum: 0
                  maximum: 6
                  example: 0
        required: true
      responses:
        200:
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Issue'
        404:
            description: 'Error: Not Found'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorExample:
                    $ref: '#/components/examples/error404'
      security:
      - ApiKeyAuth: [] 
    delete:
      tags:
      - issues
      summary: Deletes an Issue associated with the ID passed as parameter, if the ID does not exist, don't do nothing
      operationId: destroy
      parameters:
      - name: issueId
        in: path
        description: Issue id to delete
        required: true
        schema:
          type: integer
          format: int64
      responses:
        204:
          description: No content
          content:
            application/json: {}
        401:
          description: 'Error: Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error401'
      security:
      - ApiKeyAuth: [] 
  /issues/bulkForm:
    post:
      tags:
      - issues/bulk
      summary: Creates multiple new Issues
      operationId: bulkCreate
      requestBody:
        description: Provide the necessary fields to generate as Issues as you want
        content:
          application/json:
            schema:
              type: object
              properties:
                issues:
                  type: array
                  items:
                    type: object
                    properties:
                      subject:
                        type: string
                        minLength: 4
                        example: "Me mareo"
        required: true
      responses:
          200:
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Issue'
          404:
            description: 'Error: Not Found'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResult'
                examples:
                  errorExample:
                    $ref: '#/components/examples/error404'
      security:
      - ApiKeyAuth: [] 
  /issues/{issueId}/comments:
  #revisar
    get:
      tags: 
      - issues/comments
      summary: Find the comments corresponding to an Issue
      description: Returns all the comments of the specified Issue
      operationId: getCommentsByIssueId
      parameters:
      - name: issueId
        in: path
        description: ID of the Issue to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
          200:
            description: successful operation
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Comment'
          404:
            description: 'Error: Not Found'
            content:
              application/json:
                examples:
                  errorExample:
                    $ref: '#/components/examples/error404'
      #security:
      #- ApiKeyAuth: [] 
    post:
      tags:
      - issues/comments
      summary: A new user creates a new comments in a specified issue
      operationId: addComment
      parameters:
      - name: issueId
        in: path
        description: ID of the Issue to returnI
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: Provide a valid user_id and issue_id to generate a new comment with the content that you have written
        content:
          application/json:
            schema:
              required:
              - content
              - issue_id
              - user_id
              type: object
              properties:
                content:
                  type: string
                  example: 'My comment'
                issue_id:
                  type: integer
                  format: int64
                  example: 2
                user_id:
                  type: integer
                  format: int64
                  example: 2
        required: true
      responses:
        201:
          description: Comment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewComment'
        400:
          description: Something went wrong
          content:
            application/json:
              examples:
                errorExample:
                  $ref: '#/components/examples/error400'
      #security:
      #- ApiKeyAuth: [] 
  /issues/{issueId}/activities:
  #revisar
    get:
      tags: 
      - issues/activities
      summary: Find the activities corresponding to an Issue
      description: Returns all the activities of the specified Issue
      operationId: getActivitiesByIssueId
      parameters:
      - name: issueId
        in: path
        description: ID of the Issue to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
          200:
            description: successful operation
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Activity'
          404:
            description: 'Error: Not Found'
            content:
              application/json:
                examples:
                  errorExample:
                    $ref: '#/components/examples/error404'
  /issues/filter:
    get:
      tags: 
      - issues/filters
      summary: Filtrar issues
      description: Filtra los issues según los parámetros proporcionados
      parameters:
        - in: query
          name: filter_by_type
          schema:
            type: string
          description: Tipo de issue a filtrar
        - in: query
          name: filter_by_severity
          schema:
            type: string
          description: Severidad de issue a filtrar
        - in: query
          name: filter_by_priority
          schema:
            type: string
          description: Prioridad de issue a filtrar
        - in: query
          name: filter_by_status
          schema:
            type: string
          description: Estado de issue a filtrar
        - in: query
          name: filter_by_assign
          schema:
            type: string
          description: Nombre de usuario asignado al issue a filtrar
        - in: query
          name: filter_by_createdBy
          schema:
            type: string
          description: Nombre de usuario creador del issue a filtrar
      responses:
        '200':
          description: Lista de issues filtrados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Issue'
  /issues/filter_by_name:
    get:
      tags: 
      - issues/filters
      summary: Filtrar issues por nombre
      description: Filtra los issues que contienen el nombre proporcionado en el parámetro de consulta "name"
      parameters:
        - in: query
          name: subject
          schema:
            type: string
          description: Nombre del issue a filtrar
      responses:
        '200':
          description: Lista de issues filtrados por nombre
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Issue'
  /watchers:
    get:
      tags:
      - issues/watchers
      summary: Obtener lista de issues
      description: Devuelve una lista con la información de todos los watchers
      responses:
        '200':
          description: Lista de issues
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Watcher'
    post:
      tags:
      - issues/watchers
      summary: Crear un nuevo watcher
      description: Crea un nuevo watcher con la información proporcionada
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewWatcher'
      responses:
        '201':
          description: Watcher creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Watcher'
  /watchers/{watcherId}:
    delete:
      tags:
      - issues/watchers
      summary: Eliminar un watcher
      description: Elimina un watcher existente con el ID proporcionado
      parameters:
        - in: path
          name: watcherId
          required: true
          schema:
            type: integer
          description: ID del watcher a eliminar
      responses:
        '204':
          description: Watcher eliminado exitosamente
components:
  schemas:
    Issue:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 2
        subject:
          type: string
          minLength: 4
          example: 'My subject'
        description:
          type: string
          example: 'My description'
        due_date:
          type: string
          format: date-time
        blocked:
          type: boolean
        blocked_reason: 
          type: string
          example: 'blocked reaon'
        watchers:
          type: string
          example: 'Member X'
        typeIssue:
          type: integer
          minimum: 0
          maximum: 3
          example: 0
        severityIssue:
          type: integer
          minimum: 0
          maximum: 4
          example: 0
        priorityIssue:
          type: integer
          minimum: 0
          maximum: 2
          example: 0
        statusIssue:
          type: integer
          minimum: 0
          maximum: 6
          example: 0
        user_id:
          type: integer
          example: 1
        createdBy:
          type: integer
          example: 1
        _links:
          type: object
          properties:
            self:
              type: string
              format: url
              example: 'https://falta-link/issues/2/edit'
    NewIssue:
      allOf:
        - $ref: '#/components/schemas/Issue'
        - type: object
          properties:
            token:
              type: string
              example: '9656f8894781485f7e9e168584a17ec002ad77379a3e2b3ff4604b916d98c0a7'
          required:
            - token
    Comment:
      type: object
      properties:
        issue_id:
          type: integer
          format: int64
          example: 2
        user_id:
          type: integer
          format: int64
          example: 2
        content:
          type: string
          minLength: 1
          example: 'My comment'
    NewComment:
      allOf:
        - $ref: '#/components/schemas/Comment'
        - type: object
          properties:
            token:
              type: string
              example: '9656f8894781485f7e9e168584a17ec002ad77379a3e2b3ff4604b916d98c0a7'
          required:
            - token
    Activity:
      type: object
      properties:
        action:
          type: string
          minLength: 1
          example: 'New Update'
        description:
          type: string
          example: 'Value1, changed to: Value2'
        issue_id:
          type: integer
          format: int64
          example: 2
        user_id:
          type: integer
          format: int64
          example: 2
        #revisar
    Watcher:
      type: object
      properties:
        id:
          type: integer
          description: Identificador único del watcher
        issue_id:
          type: string
          description: id del issue
        user_id:
          type: string
          description: id del user
        created_at:
          type: string
          format: date-time
          description: Estado actual del issue (abierto, cerrado, en progreso, etc.)
        updated_at:
          type: string
          format: date-time
          description: Fecha y hora de creación del issue
        url:
          type: string
          description: Fecha y hora de la última actualización del issue
    NewWatcher:
      type: object
      required:
        - issue_id
        - user_id
      properties:
        issue_id:
          type: string
          description: id de la issue
        user_id:
          type: string
          description: id del user
      example:
        issue_id: 1
        user_id: 1
    ErrorResult:
      type: object
      properties:
        message: 
          type: string
          example: 'Content is too long (maximum is 280 characters)'
      required:
        - message
  examples:
    error400:
      value:
        message: "Content is too long (maximum is 280 characters)"
    error401:
      value:
        message: "You provided no token"
    error403:
      value:
        message: "You provided an invalid token"
    error404:
      value:
        message: "There is no issue with 'id'=8"
    IssueNotFound:
      value:
        messaege: "There is no issue with the indicated ID"
    UserNotFound:
      value:
        messaege: "There is no user with the indicated ID"
        
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
      
